services:
  - type: web
    name: branch-wise-school-link
    env: node
    buildCommand: npm install && npm audit fix --force && npm run build
    startCommand: npm run preview
    staticPublishPath: ./dist
    envVars:
      - key: NODE_VERSION
        value: 18.0.0
    autoDeploy: true